version: '3'
services:

  control-node:
    build: 
      context: .
      dockerfile: ./control_node/Dockerfile
      args:
        - password=ansible
    ports:
      - "22:22"
    volumes:
      - ./control_node/etc/ansible:/etc/ansible
      - ./control_node/ansible/playbooks:/home/ansible/playbooks
    tty: true
    stdin_open: true
    
  host1:
    build: 
      context: .
      dockerfile: ./host_nodes/Dockerfile
    tty: true
    stdin_open: true
  
  host2:
    build: 
      context: .
      dockerfile: ./host_nodes/Dockerfile
    tty: true
    stdin_open: true
